questions =  [
    {"id": 0, "question": "Landlords do not make any real contribution to our society.", "effects": {"right": -1}},
    {"id": 1, "question": "Billionaires should not exist.", "effects": {"right": -1}},
    {"id": 2, "question": "Money would not exist in an ideal society.", "effects": {"right": -1}},
    {"id": 3, "question": "Humans have no fixed nature.", "effects": {"right": -1}},
    {"id": 4, "question": "Education should be free and universal.", "effects": {"right": -1}},
    {"id": 5, "question": "The value of something comes from the work that goes into creating it.", "effects": {"right": -1}},
    {"id": 6, "question": "Healthcare is a right.", "effects": {"right": -1}},

    {"id": 7, "question": "The minimum wage should be abolished.", "effects": {"right": 1}},
    {"id": 8, "question": "Wages are always fair if set by the market.", "effects": {"right": 1}},
    {"id": 9, "question": "Competition is necessary for innovation.", "effects": {"right": 1}},
    {"id": 10, "question": "Investors should be rewarded for their investments.", "effects": {"right": 1}},
    {"id": 11, "question": "Stealing is never morally permissible.", "effects": {"right": 1}},
    {"id": 12, "question": "Inheritance should not be taxed.", "effects": {"right": 1}},
    {"id": 13, "question": "Capitalism is the greatest system to have ever existed.", "effects": {"right": 1}},

    {"id": 14, "question": "Freedom of speech is vital for a healthy society.", "effects": {"auth": -1}},
    {"id": 15, "question": "The government should be less involved in people’s everyday lives.", "effects": {"auth": -1}},
    {"id": 16, "question": "People should come together to form independent and self governing communities.", "effects": {"auth": -1}},
    {"id": 17, "question": "Nobody should be forced to work if they do not want to.", "effects": {"auth": -1}},
    {"id": 18, "question": "Prostitution should be legal.", "effects": {"auth": -1}},
    {"id": 19, "question": "We must severely reduce our military spending.", "effects": {"auth": -1}},
    {"id": 20, "question": "People should be free to practice any religion as long as they aren’t harming others.", "effects": {"auth": -1}},

    {"id": 21, "question": "People generally don’t know what’s best for themselves.", "effects": {"auth": 1}},
    {"id": 22, "question": "Organisations which oppose the government should be forcefully disbanded.", "effects": {"auth": 1}},
    {"id": 23, "question": "Gaining control of the state is the most important step to achieving my goals.", "effects": {"auth": 1}},
    {"id": 24, "question": "Bureaucracy is necessary for society to function.", "effects": {"auth": 1}},
    {"id": 25, "question": "Certain beliefs are too harmful to be allowed to be heard in public.", "effects": {"auth": 1}},
    {"id": 26, "question": "My values should be promoted by force if necessary.", "effects": {"auth": 1}},
    {"id": 27, "question": "Democracy hinders the government’s ability to change society for the better.", "effects": {"auth": 1}},

    {"id": 28, "question": "Abandoned property should be free to use by any individual.", "effects": {"auth": -1, "right": -1}},
    {"id": 29, "question": "Intellectual property is illegitimate.", "effects": {"auth": -1, "right": -1}},
    {"id": 30, "question": "The workplace should be more democratic.", "effects": {"auth": -1, "right": -1}},
    {"id": 31, "question": "Instead of voting for politicians, people should vote on individual issues.", "effects": {"auth": -1, "right": -1}},
    {"id": 32, "question": "People should be free to roam the landscapes of the world.", "effects": {"auth": -1, "right": -1}},
    {"id": 33, "question": "Trespassing should not be a crime.", "effects": {"auth": -1, "right": -1}},
    {"id": 34, "question": "Rehabilitation, not punishment, should be the focus of criminal justice.", "effects": {"auth": -1, "right": -1}},
    {"id": 35, "question": "Political and economic power should be dispersed amongst the population.", "effects": {"auth": -1, "right": -1}},
    {"id": 36, "question": "Executives have too much power over their workers.", "effects": {"auth": -1, "right": -1}},

    {"id": 37, "question": "Taxation is theft.", "effects": {"auth": -1, "right": 1}},
    {"id": 38, "question": "Income taxes should be reduced if not abolished.", "effects": {"auth": -1, "right": 1}},
    {"id": 39, "question": "The economy works best when government intervention is minimal.", "effects": {"auth": -1, "right": 1}},
    {"id": 40, "question": "Free trade between nations is a good thing.", "effects": {"auth": -1, "right": 1}},
    {"id": 41, "question": "“Society” does not really exist.", "effects": {"auth": -1, "right": 1}},
    {"id": 42, "question": "Selfishness can be a virtue.", "effects": {"auth": -1, "right": 1}},
    {"id": 43, "question": "Regulation can often hurt the people it aims to protect.", "effects": {"auth": -1, "right": 1}},
    {"id": 44, "question": "The trade of human organs should be legal.", "effects": {"auth": -1, "right": 1}},
    {"id": 45, "question": "Roads should be privatised.", "effects": {"auth": -1, "right": 1}},

    {"id": 46, "question": "All major industries should be nationalised.", "effects": {"auth": 1, "right": -1}},
    {"id": 47, "question": "The individual has a duty to sacrifice themselves for the good of society.", "effects": {"auth": 1, "right": -1}},
    {"id": 48, "question": "Each person should receive food rations to prevent starvation.", "effects": {"auth": 1, "right": -1}},
    {"id": 49, "question": "The government should tax goods which are harmful to society.", "effects": {"auth": 1, "right": -1}},
    {"id": 50, "question": "The economy should be directed away from producing luxuries.", "effects": {"auth": 1, "right": -1}},
    {"id": 51, "question": "Economic globalisation should be opposed.", "effects": {"auth": 1, "right": -1}},
    {"id": 52, "question": "Politics is best viewed as a struggle between groups with different interests.", "effects": {"auth": 1, "right": -1}},
    {"id": 53, "question": "Nobody can ever truly be separate from society.", "effects": {"auth": 1, "right": -1}},
    {"id": 54, "question": "Consumerism has degraded our society.", "effects": {"auth": 1, "right": -1}},

    {"id": 55, "question": "Laws should be in place to prevent workers from unionising.", "effects": {"auth": 1, "right": 1}},
    {"id": 56, "question": "Absolute monarchy is a desirable system of government.", "effects": {"auth": 1, "right": 1}},
    {"id": 57, "question": "Large organisations need a top down structure to function well.", "effects": {"auth": 1, "right": 1}},
    {"id": 58, "question": "Work makes people stronger.", "effects": {"auth": 1, "right": 1}},
    {"id": 59, "question": "Aristocratic societies were better than democratic ones.", "effects": {"auth": 1, "right": 1}},
    {"id": 60, "question": "A society without strong leaders is destined to fail.", "effects": {"auth": 1, "right": 1}},
    {"id": 61, "question": "Workers in essential parts of the economy should not be allowed to strike.", "effects": {"auth": 1, "right": 1}},
    {"id": 62, "question": "Hierarchy will arise in any society.", "effects": {"auth": 1, "right": 1}},
    {"id": 63, "question": "Only educated people should be allowed to vote.", "effects": {"auth": 1, "right": 1}},
];